### PR TITLE
test pull request - do not merge

### PR DESCRIPTION
**Pull request by jdsn**
Note: this PR will NOT be merged. It is just to check if the tests (in the master branch) are ok.

### CODE REVIEW

**Comment by jdsn** [comment]
Keeping this PR open to prove that hound works.

**Comment by jdsn** [comment]
@bmwiedemann @rsalevsky
+1 on this PR does not mean to merge it, it means that the hound config is accepted being ok

**Comment by jdsn** [comment]
@bmwiedemann @rsalevsky 
enabled hound tests and travis for spec and syntax tests - please rereview

**Comment by bmwiedemann** [comment]
in the travis rake spec tests I see
```
Error loading credentials from netrc file for https://api.github.com/
```
and it succeeds anyway. If it is a bogus error, I guess we should not show it there because it will confuse people.

**Comment by jdsn** [comment]
Yes, the credentials are not needed because the requests to the github api are mocked by a sinatra app. I agree that the error message should not show up in testing.

**Comment by jdsn** [comment]
@bmwiedemann @rsalevsky 
dropped the error message by faking a netrc file - please rereview

**Comment by bmwiedemann** [comment]
LGTM.

**Review by rsalevsky — APPROVED** [review]

**Comment by jdsn** [comment]
Closing this PR due to the reviews.

**Comment by jdsn** [comment]
reopening to rerun tests

**Comment by jdsn** [comment]
Closing again as documented above

**Pull request closed without merging**
